### ISSUE TITLE
Renaming feature

### ISSUE THREAD

**Issue by KatakiriKasai** [Dezaimasu/cute-button#12]
Hello. Can you add renaming feature? It would be handy to be able to add date prefix to images so they would be neatly sorted in a folder.

**Comment by Dezaimasu** [comment]
Working with datetime in js is a huge pain in the butt, but sure, why not, simple date or static prefix would be easy.

**Comment by Dezaimasu** [comment]
19d033e88231f738c9a41a95d856c351bcdec42f
Can't say I'm satisfied with results, proper customizable template for filename would probably be much better. Also someone asked long ago about custom filenames on boorus, with tags and stuff, would love to do that somewhere in the future.
But I hate drawing interfaces, so for now only this much. You can set text string, date and time, or timestamp as a simple prefix.

**Comment by Dezaimasu** [comment]
Собственно оно уже готово, только инструкция пока не переведена. Можно подставлять даты, код борды, номер треда, в будущем можно как-то расширить это дело. 
Буду благодарен за мнение по поводу текущего функционала.
