### ISSUE TITLE
Broken twitter downloads

### ISSUE THREAD

**Issue by KatakiriKasai** [Dezaimasu/cute-button#13]
Hello. Twitter has changed their UI for logged in users and now images have different urls and the addon can't handle them.
If you're logged out, Links are the same as usual. If you're logged in, they looks like
`https://pbs.twimg.com/media/IMAGEURL?format=jpg&name=360x360`
You get a similar url if you use https://tweetdeck.twitter.com/

If you change the url to
`https://pbs.twimg.com/media/IMAGEURL.jpg:orig`
you'll get the original image as usual.
Can you fix it?

**Comment by Dezaimasu** [comment]
Yeah, I know, gonna fix this soon. 
For now you can disable "Always save full-sized images" option.

**Comment by KatakiriKasai** [comment]
В ченджлоге вы написали про фикс твиттера. Скачивание всё ещё не работает в новом интерфейсе твиттера

**Comment by Dezaimasu** [comment]
https://files.catbox.moe/uyej4i.webm
Проверял и перепроверял, всё работает и со старым, и с новым оверлеем. Добавил на всякий случай правило чтобы и в мобильной версии, которая mobile.twitter.com, корректно обрабатывало ссылку.

Если что-то конкретное не качается, то пример страницы мог бы помочь.
Если вообще всегда не качается, то возможно дело в каком-то установленном аддоне, который модифицирует ссылку, из-за чего мой аддон не может собрать правильный урл. Тогда имя аддона может помочь.

**Comment by KatakiriKasai** [comment]
Для чистоты эксперимента отключил все дополнения, переустановил расширение и сбросил его настройки. Галочка "Всегда сохранять полноразмерные версии" стоит.

![w7Lmduy60c_1](https://user-images.githubusercontent.com/20987082/64955863-f7c12a80-d891-11e9-8eb6-2663939292da.gif)

На твидек ситуация аналогичная.
Последний твит из гифки:
https://twitter.com/waaaa_sabi/status/1173060000404475904

Использую Firefox 69.

**Comment by Dezaimasu** [comment]
Не знаю. Вот честно, извиняюсь, явно мой прокол где-то, но идей ноль. Те же ссылки, всё то же, и у меня всё работает, не могу воспроизвести проблему. Уже другие версии лисы пробовал, уже даже старые версии расширения ставил, даже в них работает. И на твитдеке в т.ч. Только в дебагер лезть остаётся.

Если вдруг есть возможность, то я мог бы через тимвьювер какой подключиться и быстро в нём глянуть какого ляда там происходит, вангую что в процессе урл исковеркало по неизвестной пока мне причине, поэтому ничего не скачивается.

Если нет возможности (или доверия), но есть немного лишнего времени, то вкратце накидал инструкцию куда идти чего нажимать:

- about:debugging
- Там в списке найти моё расширение. Если списка расширений нет, то слева нажать на "This Firefox"
- Нажать inspect/debug, откроется вкладка либо новое окно.
- Внутри вкладка Debugger
- Слева список папок с расширениями, нужен файл Cute Save Button/js/download.js
- Поставить брейкпоинт куда-нибудь в 24-ю строчку, для этого тыкнуть мышкой по номеру строчки, он станет подсвеченным.
- Переключиться на владку с тивттером, нажать мою кнопку на любой картинке которая не сохраняется.
- Переключиться обратно, строчка с брейкпоинтом будет подсвечена. Расширение сейчас остановилось в этом состоянии, если мышкой навести на слово downloadRequest, то во всплывающем окошке будет информация, с которой расширение попыталось сохранить картинку. В идеале мне нужен скриншот этих данных, в частности параметр "src".

P.S. на всякий случай, тупой вопрос, но уже не знаю чего смотреть, там не стоит чекбокс "не скачивать оригиналы"?

**Comment by KatakiriKasai** [comment]
Вот, что в downloadRequest
```originalName: null
pageInfo: {…}
showSaveDialog: false
src: "https://pbs.twimg.com/media/EEeL2F4UYAAa-kR?format=jpg&name=orig"
template: {…}
type: "download"
useOriginalName: false
<prototype>: {…}
```

Скриншот настроек. Я их сбрасывал до той гифки
![изображение](https://user-images.githubusercontent.com/20987082/64987028-f9f6a980-d8d0-11e9-8f93-0e1c2b61ab3c.png)

**Comment by Dezaimasu** [comment]
Дьявольщина какая-то.
Тогда ещё просьба, то же самое, только брейкпоинт в 94 строчку и посмотреть что после попытки сохранения будет в lastError в этой строке.
Алсо рядом с вкладкой Debugger есть вкладка Console, по идее в ней должно сообщение о какой-то ошибке появиться.
И как вариант ещё в другой, браузерной консоли, которая через Ctrl+Shift+J, может быть какой-то текст ошибки, которого нету в той консоли.

**Comment by KatakiriKasai** [comment]
В консоли много что происходит.
![изображение](https://user-images.githubusercontent.com/20987082/64988031-388d6380-d8d3-11e9-9521-dcb1118d62c7.png)

Я так понимаю, это может быть проблемой
![изображение](https://user-images.githubusercontent.com/20987082/64988092-58bd2280-d8d3-11e9-8339-ae2b686fbbab.png)

Сейчас погуглю, что можно сделать

**Comment by Dezaimasu** [comment]
Там вон справа название файла пишется, в котором ошибка произошла, моих я там не вижу. Возможно действительно в этой блокировке проблемы, по идее это моцареловская защита от слежения делает.

**Comment by KatakiriKasai** [comment]
Отключил блокировку куки - теперь работает. Ну и ну. Спасибо за помощь.

**Comment by Dezaimasu** [comment]
Как-то не подумал на печеньки даже. Хотя помню сам юматрицу когда поставил тоже вляпался в это дело, и пытался понять почему картинки не схороняются. 

К сожалению downloads апи не позволяет явно задавать куки. А тот же реферер оно вообще не передаёт никак, из-за чего в теории где-то тоже не будет работать скачивание.

А по поводу трекеров, у меня во встроенной защите от слежения только "Tracking content" выключен, остальные опции включены и пока вроде проблем не было.
