### ISSUE TITLE
Не работает сохранение для отдельного домена

### ISSUE THREAD

**Issue by nshell32** [Dezaimasu/cute-button#14]
Я тут отзыв писал https://addons.mozilla.org/ru/firefox/addon/cute-save-button/reviews/1410179/
Само расширение очень хорошее. Было. Но у меня на 68.0.1 не работает сохранение для отдельного домена. Сохраняет все равно в папку по умолчанию. 

Дополнил: Сайт pornreactor.cc. Я по document.location.hostname и скопировал имя домена.

**Comment by Dezaimasu** [comment]
Ответил в отзывах, но продублирую и сюда. В идеале бы скриншот настроек, как именно выглядит правило для этого сайта. Потому что у меня работает на 69 dev версии, и даже на 60.8.0esr, понять бы в чём проблема, исправлю обязательно.

> Сейчас попробовал, вроде бы всё сохраняет. https://files.catbox.moe/fx5yru.PNG вот так выглядит, просто pornreactor.cc и написал.
Идеи у меня две, первая - указан абсолютный путь, или какой-то другой неправильный, в который лиса не разрешает сохранять файлы, поэтому всё валится в папку по-умолчанию.
Вторая - при обновлении что-то напуталось с настройками, вероятность что я накосячил далеко не нулевая. Решение - удалить моё расширение полностью, это удалит все настройки, и потом поставить заново и с чистого листа настроить. Но потеряются все настройки.

**Comment by nshell32** [comment]
Спасибо за отзывчивость, я переустановил расширение, потом сделал как на скриншоте - все заработало. А есть ли какой-то способ сделать так, чтобы и по нажатию пробела сохранялось в выбранную папку для этого домена? Просто пробел не сработал, пробел с клавишей-модификатором тоже.

**Comment by Dezaimasu** [comment]
А с пробелом это уже точно баг, у меня тоже не работает, исправлю в ближайшее время.

**Comment by Dezaimasu** [comment]
1bf3f9aa9407ab82b49167c449ca1a185305c50d
