### ISSUE TITLE
webp support?

### ISSUE THREAD

**Issue by neodesler** [Dezaimasu/cute-button#15]
I noticed today the current version doesn't download webp images.  I'm not sure if the past versions did but this version doesn't.  :)  I wonder if anyone else had this issue.

**Comment by neodesler** [comment]
Further information:  I am using Firefox.  Here is a [link to a webp image](https://www.gstatic.com/webp/gallery/2.webp) which I try to download using a cute button from Firefox and nothing happens.  I've tried several other webp images and it doesn't work.

**Comment by Dezaimasu** [comment]
e59190b2153632c835e6360de288eb483710dab0
done
