### ISSUE TITLE
Distorts some sites

### ISSUE THREAD

**Issue by pro100Hub** [Dezaimasu/cute-button#16]
Hello.
I noticed that the extension breaks the pepper.ru website. When you hover over the image in the description, for example, here https://www.pepper.ru/deals/nabor-skovorodok-tefal-22-i-24-sm-semnaya-ruchka-42082 the site is cropped.
Example
![2019-09-18_17-02-23](https://user-images.githubusercontent.com/10475278/65260206-6f57b980-db1f-11e9-9af2-bb9f808e5ef2.gif)

Please fix. Thanks.

**Comment by Dezaimasu** [comment]
Wew, never actually thought about table markup.
Thanks for the url, fixed it, wait for the next version please. Maybe tomorrow.

**Comment by pro100Hub** [comment]
@Dezaimasu 
Thanks.

Please check one more bug. The save button appears on the thumbnails. I noticed this on many sites and always accidentally saved these pictures.
Here is one example: https://beru.ru/product/televizor-polarline-40pl52tc-sm/298111232?show-uid=15690003268156584665906011

![2019-09-20_22-27-02](https://user-images.githubusercontent.com/10475278/65346399-1870e380-dbf6-11e9-8e86-630050d70d27.gif)

**Comment by Dezaimasu** [comment]
Вроде всё исправил, обновляйте-проверяйте.

**Comment by pro100Hub** [comment]
> Вроде всё исправил, обновляйте-проверяйте.

Проверил, всё отлично! Спасибо за оперативность и шикарное расширение :handshake: 
:+1:  :1st_place_medal:
