### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Mayurifag** [Dezaimasu/cute-button#2]
Был бы очень благодарен за добавление следующих фичей:

-  Возможность менять изображение иконки сохранения. Всё-таки, «cute» для каждого является сугубо индивидуальной вещью, хочется иметь возможность поставить свою иконку (нет-нет, ваша иконка великолепна).
-  Сохранение различных типов файлов в различные директории. Так, например, хочется иметь возможность сохранять пикчи и гифки (`jpg/png/gif/...`) в папку, скажем, `~/Pictures`, а те же `webm` — в `~/Videos`.
- Возможность менять хоткеи и стандартное поведение. Так, например, при наличии возможности сохранить оригинальное название, я хотел бы иметь возможность делать это поведение дефолтным по `Left Click`.

Спасибо за разработку расширения.

**Comment by Dezaimasu** [comment]
Над первым сам думал, добавлю, если только не наткнусь на какой подводный камень в WebExtensions.

Второе будет, тут ещё был недо-реквест на тему на разные хоткеи в разные папки сохранять, наверное запилю это всё скопом.

По поводу третьего, думаю простой галочки в опциях хватит? Алсо там у меня ещё мидлклик есть незадействованный, когда для него придумаю какое-то поведение, то можно будет сделать полноценный выбор функции для каждой кнопки мыши.

**Comment by Mayurifag** [comment]
>Над первым сам думал, добавлю

Можно еще впилить _небольшой_ набор встроенных иконок. Какую-то нейтральную «стрелочку вниз» ту же.

>По поводу третьего, думаю простой галочки в опциях хватит? 

Думаю, да. Вы автор, как видите это себе, так и реализуйте. 😺 

Еще пришла в голову мысль о настройке, которая позволила бы показывать cute button только при зажатии, например, шифта. Позволило бы избежать мисскликов (я уже успел парочку сделать, хех).

Еще раз благодарю за расширение.

**Comment by Dezaimasu** [comment]
Через зажатый Shift не очень удобно, сейчас обрисую.

Допустим сделал, что только через Shift. Наводишь мышкой на картинку, понадобилась кнопка, какой логичный шаг? Правильно, нажать Shift, должна появиться кнопка. А она не появляется, потому что она срабатывает только на mouseover событии, а такого события не произошло, потому что картинка как была под курсором, так и есть, ничего не поменялось. Т.е. нужно сначала нажать Shift, а потом уже наводить курсор на нужную картинку. В вышеописанном случае нужно нажать Shift, увести мышку с картинки, и навести обратно, тогда сработает mouseover событие, оно увидит, что был зажат Shift, и кнопка появится. Не очень удобно как по мне.
Надеюсь не слишком запутанно расписал.

Накручивать же логику расширения, отдельно каждый раз запоминать какой элемент последний под курсором появился, чтобы при нажатии Shift именно на этом элементе нарисовать кнопку, это уже слишком много лишних действий нужно впихнуть, на такое я пойтить не могу.

Алсо именно такое поведение ты можешь уже сейчас сделать, в опциях поставь минимальный размер изображений, на которых будет появляться кнопка, какую-нибудь запредельную цифру. Тогда она не будет появляться, НО если зажать Shift, то эта опция игнорируется, и будет как раз именно 

> только при зажатии, например, шифта

Заодно можешь убедиться, что это не очень удобно. Хотя может это мне так кажется.

**Comment by Mayurifag** [comment]
>Надеюсь не слишком запутанно расписал.
Если бы я не _осознавал_ что такое `mouseover`, то, быть может, и не понял бы. А так, — спасибо, я попробую. Добра.

**Comment by Dezaimasu** [comment]
Пусть открытое висит пока я не прикрутил всё это.

**Comment by Dezaimasu** [comment]
278945c efc4fa1 bd53927

**Comment by Mayurifag** [comment]
Еще с 2gis проблема, каждый элемент местности считается как отдельная пикча, отключить бы там кнопку или еще какой костыль прикрутить.

Реквестирую, алсо, сохранение фулл резолюшн файла в вконтактиках и всем таком часто используемом если возможно. 

Большущее спасибо, что делаете свою работу! Умел бы я еще благодарить мотивирующе. :)

**Comment by Dezaimasu** [comment]
Для вконтактика эт можно. Твиттер наверное сюда же.

А по поводу 2gis я уже всё предусмотрел ещё давно, там есть отдельная опция со списком классов, на которых кнопка срабатывать не будет. Поначалу я это дело прибил в аддоне гвоздями, но уже после второго-третьего раза понял что так дело не пойдёт, и вынес это в отдельную настройку.
Добавь туда через пробел "leaflet-tile", этот класс там на всех кусках карты висит, и кнопка не будет срабатывать.

**Comment by Dezaimasu** [comment]
> Возможность менять изображение иконки сохранения.

Уже давно на AMO, забыл сказать.


> Так, например, при наличии возможности сохранить оригинальное название, я хотел бы иметь возможность делать это поведение дефолтным по Left Click.

1e01f7e

**Comment by Mayurifag** [comment]
>Уже давно на AMO, забыл сказать.

Круто!

А у меня следующая штука, я не знаю, возможно ли ее реализовать тривиально, но всё-таки. 
«Cute button» выступает этаким элементом на странице, который можно «выбрать» при табуляции. При таком поведении, если случайно-таки получилось выбрать и, скажем, раз 5 нажать пробел, то пикча скачается 5 раз. А хочется условную галочку в настройках, чтобы не выделялся элемент по табуляции, вот. Моё спасибо!

**Comment by Dezaimasu** [comment]
Боюсь что это даже не табуляция, на пробеле висит хоткей, который если кнопка появилась, нажимает её. Из табуляции-то его легко исключить, но не думаю что в этом проблема, моя кнопка вообще под таб не должна попадать по идее.
Сам тоже так прокалывался пару раз, пишу текст, жму пробел, а пробела нет, и так несколько раз, и на каждое нажатие картинка качалась, потому что на ней кнопка была, а мышку не увёл. Не сразу понял что происходит.

Не очень представляю, что можно с этим сделать. Убирать хоткей точно не буду, потому что много им пользуюсь, когда штук двадцать котиков открыл в отдельных вкладках, а потом Space, Ctrl+W, Space, Ctrl+W, Space, Ctrl+W, и так до позеленения. 
Скажи, когда именно у тебя это возникло, 

> раз 5 нажать пробел, то пикча скачается 5 раз

Ты текст вводил? Если да, то можно легко сделать, чтобы этот хоткей не срабатывал, если пробел нажимается когда текст вводишь.

**Comment by Mayurifag** [comment]
Хм, скорее всего вы правы. Не могу воспроизвести проблему.
Что же, буду лелеять надежды на перебиндивание хоткеев, что решит попутно и эту проблемку. 😅

**Comment by Dezaimasu** [comment]
> можно легко сделать, чтобы этот хоткей не срабатывал, если пробел нажимается когда текст вводишь.

Я смутно предстваляю, когда ещё на странице может понадобиться пробел, кроме как когда вводишь текст. Добавлю в след версии проверку.

**Comment by Mayurifag** [comment]
Кстати, по поводу временного отключения расширения, — можно же просто запилить «выключатель» для панели, где иконки других дополнений. Удобно ведь, да и реализовать, наверное, не так трудно.

**Comment by Dezaimasu** [comment]
@Mayurifag, ты ещё тут? Расскажи, как тебе видится было бы удобнее выключатель сделать. 
Я вот сделал, но он сейчас глоабально, то есть выключает-включает появление кнопки вообще во всех вкладках, плюс запоминает это состояние когда закрываешь браузер. И вот теперь думаю, может нужно было не так, а только в пределах вкладки и в пределах сессии его дёргать.

**Comment by Mayurifag** [comment]
@Dezaimasu глобально и видел, не знаю зачем это мучение с включением/выключением в каждой отдельной вкладке и сессии. При закрытии-открытии браузера хочется иметь запомненное ранее состояние, конечно.

**Comment by Mayurifag** [comment]
Да, кстати, анон, посмотри на досуге как устанавливается/обновляется расширение если у лисы будет юзерагент жму/пинуса. Я не знаю, может я и сам виноват, но автоапдейты у меня не работают до установки расово неверного юзерагента шинды, а установка была произведена благодаря письке CheckCompability. Хотя возможно ты это уже пофиксил.

**Comment by Dezaimasu** [comment]
Енто скорее всего из-за того, что когда я сабмичу расширение на АМО, то руками выбираю, что оно только для шиндошс, потому как под линухи-маки я ничего не тестировал, и не уверен на 100% что оно работает. Хотя в теории всё должно, там только одна точка соприкосновения с файловой системой, да и та не моя, а WebExt API. 

Поэтому и автоапдейт не работает наверное, оно лезет за новой версией, не находит новой версии для линухов, и ничего не обновляет. Коль говоришь что работает, то поставлю в след. версии галочку "все платформы".

Алсо рубильник уже заапрувили, в апдейте должен был появиться на панели у тебя.

**Comment by Mayurifag** [comment]
У меня сейчас 0.3.9 версия, обновленная 12.09. Обновлюсь, моё (очередное) cпасибо!
