### ISSUE TITLE
cute button no longer appears when enlarging a Twitter picture

### ISSUE THREAD

**Issue by frgmntdmmrs** [Dezaimasu/cute-button#25]
I usually use this on Twitter by first clicking on the picture itself to enlarge it (to get the full size version) and then use Cute to download images.

Was working fine just awhile ago and now the Cute button no longer appears after enlarging (however, if I rightclick --> View Image and image is opened in a standalone tab/window, Cute button appears). Maybe Twitter did some changes on their website to prevent Cute from working?

- Using Firefox 78.0.1 (64-bit).

here's an example

cute button appears here, but if I click to autodownload, it will not download full size version, so I have to click to enlarge it

![firefox_t41T5qnwj2](https://user-images.githubusercontent.com/46425060/86649285-9b113680-bfaf-11ea-9c8f-07e47e745fe0.png)

usually after clicking, we should see the cute button appear on the top right, but it doesn't appear anymore.

![9agqdwqjWq](https://user-images.githubusercontent.com/46425060/86649539-da3f8780-bfaf-11ea-860b-8dd61a0f6348.jpg)

extra tests I did on the side, but issue still persists

- changed cute button to display in various positions
- using a different cute button image
- not able to hold control+alt -> mouseOver to download automatically, since Cute doesn't detect image

**Comment by Dezaimasu** [comment]
Thanks for the report. I found why it's not working, but proper fix might take some time.

Also it SHOULD download full size version, just tested. Check the options page, there's an option exactly for this case.

**Comment by Dezaimasu** [comment]
Fixed 4c31e5c
