### ISSUE TITLE
Instagram stories and videos

### ISSUE THREAD

**Issue by jamesxmcintosh** [Dezaimasu/cute-button#26]
Is there any chance of getting support for videos and stories on Instagram?
Thanks

Examples:
https://www.instagram.com/p/CDbgOCGq2Wr/
https://www.instagram.com/stories/motogp/2369696018604042322/
https://www.instagram.com/stories/motogp/2369696018604042322/

**Comment by Dezaimasu** [comment]
Sure. It was already possible to download it, but instagram has really tricky markup, and something always breaks sometimes. I'll fix it soon.

**Comment by Dezaimasu** [comment]
eb5d79ed39931f72cabb11e92b47b7ddec671b90
