### ISSUE TITLE
Fullsized Deviantart Images Don't Detect Save Button Properly

### ISSUE THREAD

**Issue by RedBreloom** [Dezaimasu/cute-button#28]
Problem: 
When you click on an image in Deviantart it usually allows you to zoom in twice. Once to get a slightly larger version of the image in its own frame, and once more to fully enlarge this version. 
The save button only works with the first image size.
On the two larger sizes the button appears but is not clickable. And actually sometimes only downloads the preview size version if the save button is used on this one. (I am not sure if this is related because it actually says 'pre' somewhere in the filename. )
Other:
I am using Firefox 82 and I use Windows 10's native app scaling to 150%. Which may be why this hasn't been reported as an issue before. Please let me know if you need other info as I would like to be able to use this button for DA as well. It's very useful and I appreciate it immensely.

Could I add some smaller function requests too? And if so should I make them in their own git issue?

**Comment by Dezaimasu** [comment]
You can ask wherever you want, can't promise I will do it though.
