### ISSUE TITLE
Stopped supporting Instagram

### ISSUE THREAD

**Issue by mormonxyz** [Dezaimasu/cute-button#30]
It no longer downloads images from Instagram. The download just fails.
- Firefox 87

I hope this issue will be fixed soon. Also, while I'm at it, I hope you'll add a feature that lets it download IG videos as well.

Thanks! You saved me a lot of time.

**Comment by Dezaimasu** [comment]
Sadly I can't fix new videos downloading. Not possible with Extensions API.
You have to use youtube-dl or some Instagram downloading tool for videos.

**Comment by RedBreloom** [comment]
I'm not sure if anyone else is still having the issue but all my instagram dl attempts still fail. On latest version of firefox (88). (This is presuming the commit from a few days ago was the bug fix.)

**Comment by Dezaimasu** [comment]
@RedBreloom
I haven't released any of recent changes yet because I need to test everything is works fine. I will publish new version soon, maybe even today.
