### ISSUE TITLE
Does not work in browsers on the chromium engine(not counting chrome)

### ISSUE THREAD

**Issue by mehmeh1z** [Dezaimasu/cute-button#32]
**It does not work in browsers on the chromium engine(not counting chrome)**
In all others it tries to save the image as ".htm"
I was digging in the settings, but I couldn't fix it myself, or understand what I was doing wrong.
And besides that, I had a problem with custom folders.
There is no way to configure it so that it swings from a certain site to a certain folder(it seems that I did everything according to the tips in the extension, but nothing happened, after setting a custom folder, the download does not even begin)
I hope for your help and thank you in advance!

**Comment by Haurabe** [comment]
Update.
Perhaps the problem is in the site **pixiv.net**
I tried to download the image on another site and it was downloaded in a normal format, not in .htm

**Comment by Dezaimasu** [comment]
https://github.com/Dezaimasu/cute-button/issues/41
