### ISSUE TITLE
Firefox and other hard drives

### ISSUE THREAD

**Issue by wtbguest** [Dezaimasu/cute-button#34]
Hi
I came across this addon and it looked perfect for what I needed. I simply wanted a way to bypass the directory and filename setting prompt for image downloads for stints of mass downloadings. This has all the features to do it with the hotkeys and custom directories it seems.
The problem is that the folders I'd like to save to are on external hard drives, while Firefox is installed on my regular c: drive.
For example I want to set ctrl+RMB to save instantly to g:\documents\screenshots while ctrl+0+LMB (owing to mouse hotkeys, less clunky than it looks) saves to e:\documents\webm.
Trying to set this up the directory save path boxes are red outlined and trying to click Save says that absolute paths are not allowed.

Am I SOL with using this the way I was intending? The How To does mentions the paths are relative to the browsers default save directory, which I'm guessing means I can only save to different folders on the c:\ drive where mozilla is installed? Is there no way around that? If so is there perhaps another option you or anyone could suggest looking into?
This really did seem perfect but I'm having a hard time finding anything remotely close or as good (rather than just the directory problem, everything else I look at *also* has issues like no hotkeys for alternative paths, so I'm at my wits end...)

Thanks, sorry this isn't a proper issue and just a basic question.

**Comment by Dezaimasu** [comment]
Hi.
You are correct, you can’t save file to different drives. It’s a Firefox limitation, nothing I can do about it. The only way to bypass it is to use symbolic links.
 
https://en.wikipedia.org/wiki/Symbolic_link
 
Something like
mklink /D "E:\documents" "G:\documents"
depending on what you want to do. This command should be executed in CMD, and it should be run as admin.
 
That way your folder "documents" from disk G will also appear on disk E. It’s not a copy, your files are not duplicated, it’s the same folder from disk G, you can just access it from disk E as well. It’s almost like a shortcut. That way when Firefox saves something to E:\documents, it will actually be saved to G:\documents
