### ISSUE TITLE
Excluded Sites

### ISSUE THREAD

**Issue by Saectar** [Dezaimasu/cute-button#38]
I have two suggestions regarding the excluded sites:

- The button that is created in the toolbar allows to globally activate or deactivate the plugin, it would be useful if it also allowed to add the site to the list of excluded sites.
- The text box for adding excluded sites is very small, a larger text box with vertical scrolling would be better. 

Thanks .

**Comment by Dezaimasu** [comment]
I was thinking about host-specific settings myself, but still not sure how to make the UI clean and easy to use. Maybe one day.
