### ISSUE TITLE
dosnt work with pixive

### ISSUE THREAD

**Issue by Manni1000** [Dezaimasu/cute-button#41]
i am not sur if this is my fault or not. because it worked jesterday just fine. than i experimanted a bit with settings of the addon. and now everything seems to work at first  but the downlode always fails.
this is realy strange because i downloded without the addon and it worked. than i compered the downlode like from the addon and the one i donloded without the addon. strangly the downlode link is the same. but it only works when i downlode it without the addon. 
i reset all the setiings and even reinstaled the addon but the downlode are still failing.

**Comment by aurimilky** [comment]
I can confirm this bug as it getting same bug on pixiv. I chick on the button to start downloading image and then download fail. I using firefox and normal download by firefox work fine. it just failing to download any image on pixiv if I use the button.

**Comment by Manni1000** [comment]
yes the strange thing is the download link is the same but it only fails with the addon

**Comment by Dezaimasu** [comment]
ad704c9c0542dad86f7b553ea38e72a6f491abac will publish new version soon

**Comment by mehmeh1z** [comment]
> [ad704c9](https://github.com/Dezaimasu/cute-button/commit/ad704c9c0542dad86f7b553ea38e72a6f491abac) will publish new version soon

Still not working on Pivix

**Comment by Dezaimasu** [comment]
Better late than never. Uploaded this fix to the store.

**Comment by Manni1000** [comment]
it still does not work on pixive it says File wasn't available on site
