### ISSUE TITLE
[issue+feature request] Please add an option to disable the button and only use spacebar to download

### ISSUE THREAD

**Issue by fourteen-1** [Dezaimasu/cute-button#43]
Issue: dl button (bottom right) appears on top of "full-screen" button for videos and i can't full screen the video.

![firefox_ABKjbZCsdW](https://user-images.githubusercontent.com/73333396/202904438-19823afa-b1e5-4067-8467-7bb2af20d602.png) ![firefox_Bnnkpwanpl](https://user-images.githubusercontent.com/73333396/202904434-5c8ea22d-1f25-4523-a001-1e9f93be1150.png)

Possible fix: make the button appear just above the video controls bar somehow?

Feature request: Make an option to disable the button entirely and make it possible to download media via hotkey only.

thanks for the amazing extension. its made downloading images and clips a lot easier.

**Comment by Dezaimasu** [comment]
![image](https://github.com/Dezaimasu/cute-button/assets/1636242/0becb86b-5e38-4bf1-9040-f81ad048146a)
This option was created for just such cases. 
Also there's Alt+Q hotkey to hide the button.

**Comment by fourteen-1** [comment]
hide button feature is already enabled. Alt-Q seems to be a neat trick, though. Thanks.

**Comment by Thespikedballofdoom** [comment]
Alt-Q hides it when the button was already visible, and only for that image for that hover-session, but I would really like if there was a way to hide it but keep the downloading functionality active. 
I wanted to target it with CSS or uBlock temporarily, but I can't seem to actually hide it no matter what.

**Comment by Dezaimasu** [comment]
@Thespikedballofdoom 
If the option I mentioned above is not enough, you can completely hide the button by setting the horizontal offset to some really high negative value. That way it will appear off-screen, so it's functionally invisible.
![image](https://github.com/user-attachments/assets/75431474-64ab-46cf-be03-ad40968c2490)
