### ISSUE TITLE
Doesn't work with www.sex.com 

### ISSUE THREAD

**Issue by Ghostbear8P** [Dezaimasu/cute-button#45]
The button appears, but images fail to download.

I'm using Firefox 112.0 (64-bit), on windows 10, but this issue has been ongoing for over a year.

**Comment by Dezaimasu** [comment]
I believe it's fixed alongside with the other issue #41.
The button is not appearing for me on their main page, but that's another problem, and it can't be fixed without a host-specific hack, and I'm not sure I want to do add it. Once #46 will be ready you could do it yourself.
