### ISSUE TITLE
500px

### ISSUE THREAD

**Issue by ariukeera** [Dezaimasu/cute-button#50]
Привет. Спасибо за расширение. Обмазываюсь и доволен, но столкнулся с проблемой на сайте 500px.com. 

Выставил в настройках,  чтобы при сохранении изображения в имя писался title, чтобы получить файл вида dolomites-sunrise-by-mike-tesselaar ([для примера](https://500px.com/photo/1081101953/dolomites-sunrise-by-mike-tesselaar)).
Однако заметил, что заголовок страницы прогружается с задержкой, до прогрузки в нем лишь "500px". Расширение захватывает именно его. Так что для всех сохраняемых изображений получается одно и тоже название (500px.jpg).
Есть ли возможность обойти проблему?

**Comment by Dezaimasu** [comment]
починено в новой версии 5337cda
